### ISSUE TITLE
Customize logo.png

### ISSUE THREAD

**Issue by fsanzv** [Rebilly/generator-openapi-repo#12]
Hi,

I can't replace the logo.png used in redoc. I have placed the logo in /web in the master branch and it didn't work, then I placed it in /web in gh-pages branch with the same result, the default logo keeps unchanged.

This is my repo: https://github.com/SmartNodeLabs/snl-appointments-api-doc

Please can you give me some clue about what I'm doing wrong?

Best regards and thank you for your work in this project!

**Comment by RomanGotsiy** [comment]
Hi @fsanzv,

change URL to logo here: https://github.com/SmartNodeLabs/snl-appointments-api-doc/blob/master/spec/swagger.yaml#L37

This is a bug, which we will fix.

**Comment by fsanzv** [comment]
Thank you very much, solved!

Best regards
