### ISSUE TITLE
try it out button not present

### ISSUE THREAD

**Issue by fsanzv** [Rebilly/generator-openapi-repo#13]
Hi again,

I can't find the 'try it button' in my swagger-ui. I have created a new project from scratch and the button is not shown also.

Thank you in advanced.

**Comment by RomanGotsiy** [comment]
Can you make a screenshot?

**Comment by fsanzv** [comment]
Of course, here you are.

![image](https://user-images.githubusercontent.com/3636174/28207755-21b1bc8e-688b-11e7-8600-cc965cecff7e.png)

**Comment by RomanGotsiy** [comment]
Can you send your swagger file.
Most likely you don't have `host` or `securityDefinitions` configured in your spec.

Anyway, this is [swagger-ui](https://github.com/swagger-api/swagger-ui) so consider opening an issue in their repo.
