### ISSUE TITLE
We found potential security vulnerabilities in your dependencies.

### ISSUE THREAD

**Issue by dschniepp** [Rebilly/generator-openapi-repo#32]
Unfortunatly the generator package is affected by the issue related to the "event-stream" incident. Are you already in preparations to fix this issue or shell try to make an pr?

- [x] __event-stream__ used by https://github.com/AveVlad/gulp-connect
- [ ] __deep-extend__ due to sway used by https://github.com/Rebilly/swagger-repo

**Comment by RomanGotsiy** [comment]
Do you mean the package itself or the repository which is the result of the package output?

If you can quickly prepare a PR would be just awesome!

**Comment by dschniepp** [comment]
The result of the package output. PR is coming.

**Comment by dschniepp** [comment]
I closed this issue, due to the upcoming release mentioned in https://github.com/Rebilly/swagger-repo/pull/10#issuecomment-445185438.
